### ISSUE TITLE
Password Issue

### ISSUE THREAD

**Issue by Legend95** [HerculesWS/FluxCP#26]
I am having an error in creating a new account.
Password doesn't match to the server sql.
For example... 
I created an account like this:
password: qwert12345

After creating it, i tried to login but i cannot so i check my sql and the registered password is : 88ca80df2d72dbebcef83a756c323da1

How to fix this?

**Comment by MatiasSW** [comment]
You need to disable md5 either at the server or at FluxCP, in any case, it needs to be the same settings on both ends. 

FluxCP go config/servers.php L48 (It is on/true by default)
Hercules go to conf/login-server.conf L81 (It is no/false by default)
