### ISSUE TITLE
FluxCP Size

### ISSUE THREAD

**Issue by SamuelHercules** [HerculesWS/FluxCP#35]
how come hercules' fluxcp is 58.7mb while rathena's fluxcp is just 10mb?

![compare](https://cloud.githubusercontent.com/assets/5112338/12219700/e6073324-b703-11e5-819f-e0221f98e56a.png)

**Comment by MishimaHaruna** [comment]
From what I see, the difference is in the commit history. Our fork carries 652 commits, starting from the original FluxCP (August 2008). rathena/FluxCP only has 132 commits, without any previous history (November 2013)

If the folder size matters, consider a shallow clone (`git clone --depth 1 https://github.com/HerculesWS/FluxCP.git`). It should reduce the size to about 4.5MB.

```
4.5M    herculesws-FluxCP-shallowclone
 59M    herculesws-FluxCP
9.4M    rathena-FluxCP
9.2M    rathena-FluxCP-shallowclone
```
