### ISSUE TITLE
Upgrade to Google reCaptcha V2

### ISSUE THREAD

**Issue by Lavenblade** [HerculesWS/FluxCP#46]
Google has dropped support of reCaptcha V1. While V1 is still functional, it is not as effective as the improved Google reCaptcha V2.

**Comment by Ridley8819** [comment]
@Mysteries

**Comment by Lavenblade** [comment]
I've decided to take on the role of upgrading to Google reCaptcha V2 as long as everyone is okay with the implementation. It shouldn't take too long to do and when I'm done I'll create a pull request.

I'm new to Git and I'm not very familiar with Hercules/FluxCP but I think I can manage. Just moving a bit slower as I look at how reCaptcha was originally implemented.

**Comment by Asheraf** [comment]
maybe check this rathena/FluxCP@ea6b22f5bb31afdc4402cda91260a6e016279319

**Comment by Mysteries** [comment]
Has been merged c83e979 Thanks 👍
